---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-client-ruby
  name: prometheus-client-ruby
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-client-ruby
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-client-ruby
    spec:
      containers:
      - image: localhost:5000/prom_client_ruby
        imagePullPolicy: Always
        name: prometheus-client-ruby
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    monitoring: prometheus
    app: prometheus-client-ruby-svc
  name: prometheus-client-ruby-svc
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app: prometheus-client-ruby
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-client-ruby
  name: prometheus-client-ruby
spec:
  endpoints:
  - interval: 5s
    port: http
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: prometheus-client-ruby-svc
      monitoring: prometheus